### PR TITLE
sql_assignment_1

### PR DESCRIPTION
**Pull request by anisess10**
## Checklist
- [ Y] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by efantinatti — CHANGES_REQUESTED** [review]
Dear Anis Bouazra

Session 1:
1 - Missing the Session 1.

Session 2:
2 - OK.

Session 3:
3 - OK.

Final:
4 - Recomended you to review your Session 1 before merging your feature branch 'assignment-one' to 'main'. Sent for review.

Mark: 20 points.

**Comment by anisess10** [comment]
> Session 1: 1 - Missing the Session 1.
> @efantinatti Thank you for your feedback, and my apologies for forgetting to attach Part 1 of the assignment earlier. Please find my answer attached now.
ERP

**Comment by anisess10** [comment]
> Final: 4 - Recomended you to review your Session 1 before merging your feature branch 'assignment-one' to 'main'. Sent for review.

I thought i followed the submission instructions by creating a pull request from my  assignment branch to my fork's main branch
PR

**Comment by efantinatti** [comment]
Thank you Anis Bouazra. Approved. Please merge it to your main branch.

**Pull request merged**
